baseURL: https://atakan-erdogdu.netlify.app/
languageCode: en-us
title: Portfolio Website for Atakan Erdogdu
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Start Exploring
    subtitle: |-
      FEEL FREE TO EXPLORE MY WEBSITE TO GET TO KNOW ME AND THE PROJECTS I WORKED ON
    title: Hi, my name is Atakan!
    blog: {}
    contact:
    address:
      - city: London, NW1
        country: United Kingdom
        street: Regent's Park
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: aerdogdu.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (+44) 7391960555
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  #You run by blogdown::serve_site()
  footer:
    copyright: Atakan Erdogdu
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
#      - icon: fa-twitter
#        label: Twitter
#        url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/atakan.erdogdu
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/atakannerdogdu/
      - icon: fa-github
        label: GitHub
        url: https://github.com/AtakanErdogdu
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/atakan-erdogdu/
  image: ''
  name: Atakan Erdogdu
  navigation:
    button1:
      - name: Get Started
        url: blogs
    links:
      - name: Home
        url: '#'
    menu: Menu
    subtitle: MFA2022
    title: Atakan Erdogdu
  tiles:
    enable: yes
    showcase:
      - image: portrait.jpeg
        subtitle: Allow me the courtesy to introduce myself
        title: About me
        url: blogs/about_me
      - image: work_background.jpg
        subtitle: Education and professional experiences
        title: Cirriculum Vitae
        url: blogs/resume
      - image: beverages.jpg
        subtitle: How did the prices evolve over time?
        title: Decomposing the Consumer Price Index
        url: blogs/cpi
      - image: tflbikes.jpg
        subtitle: How did COVID19 Affect Bike Rentals in London?
        title: TfL Bike Rentals
        url: blogs/bike_rentals
      - image: stocks.jpg
        subtitle: Yield Curve Inversion as a Predictor of Recessions
        title: Predictive Power of the Yield Curve
        url: blogs/yield_curve
      - image: pytest.jpg
        subtitle: A Supervised Machine Learning Model in Python
        title: Predicting Direction of Stock Price Returns
        url: blogs/pytest
  two:
    buttonText: Download My Paper
    enable: yes
    subtitle: I recently valued Intel using different valuation methodologies that range from DCF, comparables, Black-Scholes liquidation value, and Monte Carlo simulation.
    title: My valuation analysis of Intel
    url: https://drive.google.com/file/d/1PxiA16DKEAM3e0e3rK_t8FOH9nWFIIku/view?usp=sharing
